# 服务器HTTP监听地址
listen = ":8080"
# 静态资源路径，例如：/root/bepusdt/static；通过此参数可自定义模板，参考static目录，如非必要不建议修改。
static_path = ""
# SQLite数据库路径
sqlite_path = "/var/lib/bepusdt/sqlite.db"
# 日志输出路径
output_log = "/var/log/bepusdt.log"